services:
  postgres:
    extends:
      file: docker-compose.common.yaml
      service: postgres
    environment:
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
  api:
    extends:
      file: docker-compose.common.yaml
      service: api
    image: common-app:dev
    build:
      context: .
      target: development
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/devdb
      - 'AUTH0_API_CONFIG={"domain":"${AUTH0_DOMAIN}", "clientId": "${AUTH0_CLIENT_ID}", "clientSecret": "${AUTH0_CLIENT_SECRET}"}'
      - 'AUTH0_EXPRESS_CONFIG={"audience":"${AUTH0_AUDIENCE}", "issuerBaseURL": "${AUTH0_ISSUER}"}'
      - PORT=3000
      - SENTRY_DSN=
      - WEB_URL="https://head.common-app-frontend.pages.dev"
    ports:
      - "3000:3000"
    command: "pnpm debug"
    depends_on:
      - postgres
  prisma-studio:
    container_name: prisma-studio
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/devdb
    ports:
      - "5555:5555"
    build:
      context: .
      dockerfile: db/prisma/Dockerfile
    volumes:
      - ./db/prisma:/app/prisma
    profiles:
      - tools
    depends_on:
      - postgres
  test-postgres:
    extends:
      file: docker-compose.common.yaml
      service: postgres
    environment:
      - POSTGRES_DB=testdb
    profiles:
      - test
  test-api:
    extends:
      file: docker-compose.common.yaml
      service: api
    image: common-app:test
    build:
      context: .
      target: test
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:password@test-postgres:5432/testdb
      - 'AUTH0_API_CONFIG={"domain":"${AUTH0_DOMAIN}", "clientId": "${AUTH0_CLIENT_ID}", "clientSecret": "${AUTH0_CLIENT_SECRET}"}'
      - 'AUTH0_EXPRESS_CONFIG={"audience":"${AUTH0_AUDIENCE}", "secret":"mysupersecretsecret", "tokenSigningAlg":"HS256", "issuer": "${AUTH0_ISSUER}/"}'
      - SENTRY_DSN=
    profiles:
      - test
    depends_on:
      - test-postgres
    # command: scripts/test-command.sh # TODO: Uncomment when ready to add in testing
