services:
  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  api:
    image: common-app
    build:
      context: .
      target: development
    working_dir: /api
    environment:
      - PORT=3000
    volumes:
      - .:/api
