name: 'hightouch_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'hightouch_dbt'

model-paths: ['models']
test-paths: ['tests']

target-path: 'target' # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - 'target'
  - 'dbt_packages'
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
