---
name: API test

on:
  push:
    branches:
      - 'renovate/**'
    paths-ignore:
      - 'tf/**'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'tf/**'
      - '.github/**'
    branches-ignore:
      - 'renovate/**'

permissions:
  id-token: write
  contents: read

# This concurrency setting means that we'll never run more than one build per PR branch, even
# with rapid-fire commits.
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/job-test.yml
    secrets: inherit

  build-image:
    uses: ./.github/workflows/build-workflow.yml
    needs:
      - test
    with:
      env: 'dev'

  # Github required checks are based on the JOB name, and reusable workflows always muck with
  # job names, so we create a consistent job name here.
  status:
    name: Run tests
    needs: [test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.test.result }}"
      - run: exit 1
        if: needs.test.result != 'success'
