---
name: Build and test

on:
  push:
    branches:
      - 'renovate/**'
    paths-ignore:
      - 'tf/**'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'tf/**'
      #- '.github/**'
    branches-ignore:
      - 'renovate/**'

permissions:
  id-token: write
  contents: read

concurrency:
  group: '${github.workflow}-${github.ref}'
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  status:
    name: Run tests
    needs: [test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success"
        if: needs.test.result == 'success'
      - run: |
          echo "${{ needs.test.result }}"
          exit 1
        if: needs.test.result != 'success'
