---
name: Deploy Image

run-name: Deploy to ${{ inputs.env }}

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to deploy'
        type: string
        required: true
      env:
        description: 'Environment to deploy to'
        type: string
        required: true
    secrets:
      TF_API_TOKEN:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: "${{ inputs.env == 'prod' && format('{0}-ext', inputs.env) || format('{0}',inputs.env) }}"
  ECS_CLI_TASK: capp-${{ inputs.env }}-cli
  ECS_API_TASK: capp-${{ inputs.env }}-api

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    environment:
      name: ${{ inputs.env }}
      url: https://capp-api.${{ inputs.env }}.apps.futurestech.cloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf/envs/${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars[format('{0}_AWS_PLAN_ROLE', inputs.env)] }}
          role-session-name: GithubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull image and get labels
        id: labels
        env:
          IMAGE: '${{ inputs.image }}'
        run: |
          docker pull "$IMAGE"
          RELEASE_SHA="$(docker image inspect -f json "$IMAGE" | jq '.[].Config.Labels."org.opencontainers.image.revision"' -r)"
          echo "RELEASE_SHA=${RELEASE_SHA}" >> $GITHUB_ENV

      - name: Get latest image build tag
        id: prev-image
        run: |
          PREV_IMAGE=$(aws ecs describe-task-definition --task-definition "$ECS_API_TASK" | jq -r .taskDefinition.containerDefinitions[0].image)
          echo "prev-image=${PREV_IMAGE}" >> $GITHUB_OUTPUT

      # To update our CLI task. This is a no-op on our API task.
      - name: CLI Terraform Apply
        run: |
          terraform apply -auto-approve -input=false \
            -var 'cli_image=${{ inputs.image }}' \
            -var 'image=${{ steps.prev-image.outputs.prev-image }}'

      ## REMOVE prisma migrate resolve after this runs once in dev/prod!
      - name: Apply Prisma migration
        id: prisma-init
        run: |
          set -euo pipefail
          run_result=$(aws ecs run-task \
            --cluster "$ECS_CLUSTER" \
            --task-definition "$ECS_CLI_TASK" \
            --overrides '{"containerOverrides": [{"name": "capp-cli", "command": ["pnpm", "prisma", "migrate", "deploy"]}]}')
          echo ${run_result}
          container_arn=$(echo $run_result | jq -r '.tasks[0].taskArn')
          aws ecs wait tasks-stopped \
              --cluster "$ECS_CLUSTER" \
              --tasks "${container_arn}"
          exit $(aws ecs describe-tasks \
            --cluster "$ECS_CLUSTER" \
            --tasks "${container_arn}" | jq -r .tasks[0].containers[0].exitCode)

      # Start API task again with our updated database
      - name: API Terraform Apply
        run: |
          terraform apply -auto-approve -input=false \
          -var 'cli_image=${{ inputs.image }}' \
          -var 'image=${{ inputs.image }}'

      - name: Set sentry release
        env:
          SENTRY_AUTH_TOKEN: '${{ secrets.SENTRY_AUTH_TOKEN }}'
          SENTRY_PROJECT: '${{ vars.SENTRY_PROJECT }}'
          SENTRY_ORG: '${{ vars.SENTRY_ORG }}'
        run: |
          curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.21.2" sh
          sentry-cli releases deploys "$RELEASE_SHA" new -e "${{ inputs.env }}"
