name: Job - Test

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:18-slim

    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql://capp_admin:password@postgres:5432/testdb
      APP_ENV: dev
      AUTH0_API_CONFIG: '{"domain": "${{ vars.AUTH0_DOMAIN }}", "clientId": "${{ vars.AUTH0_CLIENT_ID }}", "clientSecret": "${{ secrets.AUTH0_CLIENT_SECRET }}"}'
      AUTH0_EXPRESS_CONFIG: '{"secret": "mysupersecretsecret", "issuer": "https://capp-issuer", "tokenSigningAlg": "HS256", "audience": "auth0.capp.com"}'
      PORT: 3000
      SENTRY_DSN: ${{ vars.SENTRY_DSN }}
      UPLOAD_BUCKET: ${{ vars.UPLOAD_BUCKET }}

    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: capp_admin
          POSTGRES_DB: testdb
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          DATABASE_URL: postgresql://capp_admin:password@postgres:5432/testdb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars['DEV_AWS_PLAN_ROLE'] }}
          role-session-name: GithubActions
          mask-aws-account-id: false

      - name: Install openssl
        run: apt-get update && apt-get install -y openssl

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build packages directory
        run: pnpm -r --filter ./packages/schemas run build

      - name: Run linters
        run: ./scripts/lint-command.sh

      - name: Apply prisma migrations
        run: pnpx prisma migrate deploy

      - name: Run type checks
        run: pnpm check

      - name: Run tests
        run: ./scripts/test-command.sh
