---
name: Run Seed Script

run-name: Run seed script in ${{ inputs.env }}

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to deploy'
        type: string
        required: true
      env:
        description: 'Environment to deploy to'
        type: environment
        required: true

env:
  AWS_REGION: us-east-1
  ECS_CLI_TASK: capp-${{ inputs.env }}-cli
  ECS_API_TASK: capp-${{ inputs.env }}-api
  ECS_CLUSTER: ${{ inputs.env }}
  VPC_STACK_NAME: ${{ inputs.env }}-vpc

permissions:
  id-token: write
  contents: read

jobs:
  seed:
    name: Run seed script in ${{ inputs.env }}
    if: ${{ inputs.env == 'dev' }}
    concurrency: ${{ inputs.env }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf/envs/${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: "${{ vars[format('{0}_AWS_PLAN_ROLE', inputs.env)] }}"
          role-session-name: GithubActions

      - name: Run dev seed script
        id: seed-db
        run: |
          set -euo pipefail
          SUBNET0=$(aws cloudformation describe-stacks --stack-name $VPC_STACK_NAME \
            --query 'Stacks[0].Outputs[?OutputKey==`PrivateSubnet0`].OutputValue' --output text)
          SECURITY_GROUP=$(aws cloudformation describe-stacks --stack-name $VPC_STACK_NAME \
            --query 'Stacks[0].Outputs[?OutputKey==`LBHostSecurityGroup`].OutputValue' --output text)
          run_result=$(aws ecs run-task \
            --cluster "$ECS_CLUSTER" \
            --task-definition "$ECS_CLI_TASK" \
            --overrides '{"containerOverrides": [{"name": "capp-cli", "command": ["pnpm", "prisma", "db", "seed"]}]}' \
            --launch-type FARGATE \
            --network-configuration "{\"awsvpcConfiguration\":{\"subnets\":[\"${SUBNET0}\"], \"securityGroups\":[\"${SECURITY_GROUP}\"]}}" )
          echo ${run_result}
          container_arn=$(echo $run_result | jq -r '.tasks[0].taskArn')
          aws ecs wait tasks-stopped \
              --cluster "$ECS_CLUSTER" \
              --tasks "${container_arn}"
          exit $(aws ecs describe-tasks \
            --cluster "$ECS_CLUSTER" \
            --tasks "${container_arn}" | jq -r .tasks[0].containers[0].exitCode)
